### ISSUE TITLE
LastOnline causing crashes to occur

### ISSUE THREAD

**Issue by RobinRMC** [RobinRMC/VencordPlus#23]
LastOnline is causing crashes.

![image](https://github.com/RobinRMC/VencordPlus/assets/76058290/42156096-b550-4f89-9270-ab7c79dde313)

**Comment by D3SOX** [comment]
I dunno but it might be BetterActivities because it broke and I fixed it yesterday. Try to update it using the latest source from https://github.com/D3SOX/vc-betterActivities

**Comment by RobinRMC** [comment]
This issue has been resolved.
