### ISSUE TITLE
ChannelTabs

### ISSUE THREAD

**Issue by KaKi87** [RobinRMC/VencordPlus#27]
### Link

https://github.com/Vendicated/Vencord/pull/499

### Description

Adds tabs and bookmarks to Discord, just like in a normal web browser.

### Agreement

- [X] I have read the above and made sure my plugin request is clear and concise.
- [X] I have checked the [existing plugins in Vencord](https://vencord.dev/plugins) and the [existing plugins in Vencord+](https://github.com/RobinRMC/VencordPlus/tree/main/src/plusplugins) and made sure the plugin I want to request hasn't already be added.
- [X] I have searched the [existing plugin requests of Vencord](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and the [existing plugin requests of Vencord+](https://github.com/RobinRMC/VencordPlus/issues?q=is%3Aissue+label%3AAddition) and made sure the plugin I want to request hasn't already been requested.

**Comment by KaKi87** [comment]
Thanks

**Comment by RobinRMC** [comment]
> Thanks !

No problem!
