### ISSUE TITLE
SimplifiedProfileNotes causes crash when loading profile pop-out or user profile in DMs

### ISSUE THREAD

**Issue by RobinRMC** [RobinRMC/VencordPlus#38]
It is <del>still un</del>known which plugin causes this crash to happen<del>, but a workaround has been found</del>!

If you first open a random user's full profile, the crash will not occur when opening profile pop-outs in the members list.

<del>If you find out which plugin causes this crash to occur, please post the name of the plugin as a comment on this issue.</del>

**Comment by WarpedWartWars** [comment]
i'm not sure if this is the same bug but when i look at a dm (and i think specifically when it loads the profile), i get this error
![image](https://github.com/user-attachments/assets/ecca0cab-a09c-47b9-848a-a4fbd246c2d4)

**Comment by RobinRMC** [comment]
I'm gonna troubleshoot this.

**Comment by RobinRMC** [comment]
SimplifiedProfileNotes causes the issue.

**Comment by RobinRMC** [comment]
https://github.com/Sqaaakoi/Vencord/issues/3

**Comment by RobinRMC** [comment]
This issue has been resolved with commit 3facc87876c5f02b2e099f3c1728d2132500ec94.
