### ISSUE TITLE
Vesktop+ - Can't screenshare

### ISSUE THREAD

**Issue by kaxlabs** [RobinRMC/VencordPlus#46]
### Discord Username

kaxon

### What happens when the bug or crash occurs?

I'd make this issue in VesktopPlus repo, but there isn't an issues section.

When I click the screenshare button, nothing happens.

### What is the expected behaviour?

Screenshare button works.

### How do you recreate this bug or crash?

1. Use Windows 11
2. Build and install VesktopPlus to stable
3. Try to screenshare (issue happens without any plugins enabled)

### Errors

I get the following errors in console when I click the screenshare button:
```
Uncaught ReferenceError: Vesktop is not defined
    at Vesktop.Components.ScreenShare.openScreenSharePicker
Uncaught (in promise) AbortError: Error starting capture
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by RobinRMC** [comment]
Issues are intentionally disabled on the repository of Vesktop+. Vesktop+ doesn't really modify code and shouldn't have any issues Vesktop doesn't.

I'll look into this, because it might have something to do with something I have renamed, but it's weird that I haven't come across this issue myself.

**Comment by RobinRMC** [comment]
I'll continue investigating this issue on Friday or Saturday.

**Comment by RobinRMC** [comment]
Does the window/screen picker not open at all?

**Comment by kaxlabs** [comment]
> Does the window/screen picker not open at all?

Correct, it's as if the button isn't functional.

**Comment by RobinRMC** [comment]
I just tested it on my own installation and it seems to work fine. Are you using the latest version of Vesktop+?

**Comment by kaxlabs** [comment]
Strange, and yes. I ran `pnpm start` and here's the full log when I try to screenshare:
```
C:\Users\Kaxon\Desktop\Vesktop\VesktopPlus>pnpm start

> vesktopplus@1.5.3 start C:\Users\Kaxon\Desktop\Vesktop\VesktopPlus
> pnpm build && electron .


> vesktopplus@1.5.3 build C:\Users\Kaxon\Desktop\Vesktop\VesktopPlus
> tsx scripts/build/build.mts


Skip checkForUpdates because application is not packed and dev update config is not forced
checkForUpdatesAndNotify called, downloadPromise is null
Error occurred in handler for 'VencordPluginNative_MessageLoggerEnhanced_getRepoInfo': Error: ENOENT: no such file or directory, scandir 'C:\Users\Kaxon\AppData\Roaming\vesktopplus\sessionData\src\userplugins'
    at async readdir (node:internal/fs/promises:948:18)
    at async VencordDesktopMain:20:2682
    at async de (VencordDesktopMain:20:2930)
    at async ti (VencordDesktopMain:20:3276)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:86658) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\Kaxon\\AppData\\Roaming\\vesktopplus\\sessionData\\src\\userplugins'
}
[22104:1106/125418.450:ERROR:ffmpeg_common.cc(970)] Unsupported pixel format: -1
Error during screenshare picker ReferenceError: Vesktop is not defined
    at <anonymous>:1:1
(node:27316) UnhandledPromiseRejectionWarning: TypeError: Video was requested, but no video stream was provided
    at VCDMain:87:5739
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:27316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)```

**Comment by kaxlabs** [comment]
I tested that and the screensharing menu appears to work on that one, but it has a strange issue of getting stuck RTC Connecting on all calls. Probably irrelevant though since the latest build doesn't have that issue.

**Comment by RobinRMC** [comment]
I don't have an issue with RTC Connecting getting stuck. Strange...

**Comment by RobinRMC** [comment]
I'll look into this when the next Vesktop update gets released.

**Comment by RobinRMC** [comment]
I have just confirmed this being an issue on the latest release build.

**Comment by RobinRMC** [comment]
@kaxlabs, can you test if the issue is still present when compiling the latest source code?

**Comment by kaxlabs** [comment]
Appears fixed thanks for looking into it.
