### ISSUE TITLE
Vencord+ plugins don't work anymore

### ISSUE THREAD

**Issue by Killua81** [RobinRMC/VencordPlus#48]
### What happens when the bug or crash occurs?

None of the Vencord+ plugins are functioning, and the Vencord+ menu remains visible despite disabling all plugins. The issue persists regardless of these changes.

### What is the expected behaviour?

I expect vencord+ working again

### How do you recreate this bug or crash?

just by launchin discord

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by RobinRMC** [comment]
I'll work on this on Friday or Saturday.

**Comment by Killua81** [comment]
Thank you !

**Comment by RobinRMC** [comment]
I have already started fixing plugins.

**Comment by RobinRMC** [comment]
I have released the first set of fixed plugins on a separate branch.

**Comment by Killua81** [comment]
Great job ! I'm waiting for better microphone and better screenshare plugin

**Comment by RobinRMC** [comment]
I've pushed the second wave of (possible) fixes.

**Comment by RobinRMC** [comment]
I'm pushing the fixes to the [fix-plusplugins](https://github.com/RobinRMC/VencordPlus/tree/fix-plusplugins) branch for now. When I'm done, I'll push them to the [main](https://github.com/RobinRMC/VencordPlus/tree/main) branch.

**Comment by Killua81** [comment]
Thank you for all your work

**Comment by RobinRMC** [comment]
I can't really program myself, so I just try to apply the most common fixes. It might not work for some plugins, but at least I get a lot of plugins working again.

I also add fixes from [Equicord](https://github.com/Equicord/Equicord). (Thanks for putting so much time and effort into this, @thororen1234!)

**Comment by RobinRMC** [comment]
I have pushed the fixes to [main](https://github.com/RobinRMC/VencordPlus/tree/main) branch with commit a214716a881b4c851620ed37b7be589959437487.
