### ISSUE TITLE
Trying to Find Channel Tabs but none Appear :(

### ISSUE THREAD

**Issue by RogalDoe** [RobinRMC/VencordPlus#49]
Hello Comrade did you changed the name of Channel Tabs or is just not there anymore ?

**Comment by RobinRMC** [comment]
ChannelTabs is still in Vencord+. The name does not contain a space.

Can you tell me if you are able to find it?

**Comment by RogalDoe** [comment]
> ChannelTabs is still in Vencord+. The name does not contain a space.
> 
> Can you tell me if you are able to find it?


No im not able to find it, that not showing it :( 
![Capture](https://github.com/user-attachments/assets/d20213a2-926b-424e-b4f5-4fa3728f8949)

**Comment by RobinRMC** [comment]
I'll park this issue and will ask you to check it again after I've fixed the other ongoing issues.

**Comment by RogalDoe** [comment]
> I'll park this issue and will ask you to check it again after I've fixed the other ongoing issues.

No problem comrade in case i gift you thes info if needed the version i have i downloaded from your Release (Latest) Page 

And the version i have are this one i changed nothing 

![Capture](https://github.com/user-attachments/assets/46d282d0-e9d2-4ac5-81f0-b0fb598e2baf)

**Comment by kaxlabs** [comment]
I noticed a few plugins aren't existing on VesktopPlus compared to regular VencordPlus. ChannelTabs exists on my VencordPlus installation. Could be relevant.

**Comment by RobinRMC** [comment]
I think that is unrelated, but interesting. I'm using Vesktop+ myself and can find ChannelTabs just fine.

![Image](https://github.com/user-attachments/assets/7184a1b1-5731-42d9-8825-845be1ffb119)

**Comment by RogalDoe** [comment]
I will try to remove all trace of Vesktop and install again with your Vesktop-Setup-1.5.3.exe 

And i advise you after in 5 min

> I think that is unrelated, but interesting. I'm using Vesktop+ myself and can find ChannelTabs just fine.
> 
> ![Image](https://private-user-images.githubusercontent.com/76058290/383745913-7184a1b1-5731-42d9-8825-845be1ffb119.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MzY2MjgsIm5iZiI6MTczMDkzNjMyOCwicGF0aCI6Ii83NjA1ODI5MC8zODM3NDU5MTMtNzE4NGExYjEtNTczMS00MmQ5LTg4MjUtODQ1YmUxZmZiMTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDIzMzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNWRmZTNmMGM2ZDI4YzE2ZTM1NzZhNzZlZDM0NjhlZmE5YjY3MjBjNWZjNzBmMmIwNWQxZjBkOTZmZDExYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5h_li7R_Jii2XN_b15sKF5Nzx_5HyiNZNJTYQedex4k)

**Comment by RogalDoe** [comment]
OK o_O I have it now 
![Capture](https://github.com/user-attachments/assets/4b964c3c-25e3-4678-8e7c-38e8b6edc538)
![Capture0](https://github.com/user-attachments/assets/2138dced-7760-4bb6-8218-80227df31c40)

**Comment by RogalDoe** [comment]
I think that wase on sessionData something conflicted when i back the one from Roaming

**Comment by RobinRMC** [comment]
Alright. I'll close this issue now.
