### ISSUE TITLE
ChannelTabs doesn't load

### ISSUE THREAD

**Issue by zany130** [RobinRMC/VencordPlus#61]
### Discord Username

zany130

### What happens when the bug or crash occurs?

enabling channel tabs does nothing

### What is the expected behaviour?

channel tabs loads and you get multiple tabs

### How do you recreate this bug or crash?

1. enable channel tabs
2. restart discord
3. notice channel tabs does not load

### Errors

```
Uncaught (in promise) Error: Error invoking remote method 'VencordPluginNative_MessageLoggerEnhanced_getRepoInfo': Error: ENOENT: no such file or directory, scandir '/var/home/zany130/.config/vesktop/sessionData/src/plusplugins'

noTrack.ts:113 Uncaught Error: Sentry successfully disabled
    at Function.set (noTrack.ts:118:23)
    at sentry.cfce268cb6a23096fe6e.js:453:37896
    at sentry.cfce268cb6a23096fe6e.js:453:38435

1320997343163580517:1 [Deprecation] Custom state pseudo classes have been changed from ":--emojiinputhorizontalpadding" to ":state(emojiinputhorizontalpadding)". See more here: https://github.com/w3c/csswg-drafts/issues/4805
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by RobinRMC** [comment]
ChannelTabs is working fine on my machine.

**Comment by zany130** [comment]
After disabling and re enabling channel tabs

I noticed that it briefly works but then the tabs disappear when navigating between them

**Comment by RobinRMC** [comment]
It functions correctly on my end.

**Comment by RobinRMC** [comment]
I have asked someone else if they experience any problems with ChannelTabs, but the plugin works fine on their end as well.

**Comment by zany130** [comment]
https://github.com/user-attachments/assets/ec7b9983-5cf7-4126-98c3-f5f2408bf0b5

here a video of the issues as you can see disabling the plugin and then enabling temporary fixes it but the tabs disappear

**Comment by RobinRMC** [comment]
I have confirmed this being an issue when using [FVUI](https://github.com/FeoreV/Themes/blob/main/Discord/Release/FVUI.theme.css). Disable the theme and see if the issue is still present.

**Comment by zany130** [comment]
Yup your right didn't now themes could break something like that

**Comment by RobinRMC** [comment]
FVUI glitches out my BetterDiscord installation, so I don't use it anymore. It keeps going back in time in a chat. (Constantly loading older messages.)

I'm happy that we've found the issue. Let's hope the author of FVUI can fix the bug(s).

I will keep this issue unlocked for a month.
